on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  uitest:
    name: uiTest
    runs-on: ubuntu-latest

    container:
      image: node:20

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm start &
        env:
          API_URL: ${{ secrets.API_URL }}
      
      - name: Wait for server
        run: sleep 10
  
      - name: Run UI tests
        run: npm run ui-test