name: Run UI Tests
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20
 
    - name: Install dependencies
      run: npm install
 
    - name: Start server
      run: npm start &
      env:
        API_URL: ${{ secrets.API_URL }}
    
    - name: Wait for server
      run: sleep 10
 
    - name: Run UI tests
      run: npm run ui-test